server:
  port: 8081
spring:
  application:
    name:
  datasource:
    driver-class-name: 
    username: 
    password: 
    url: 
    type: 

  data:
    redis:
      host: 
      port: 
      password: 

  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl:

eureka:
  client:
    service-url:
      defaultZone: 

alinfo:
  oss-endpoint: 
  oss-accesskeyid:
  oss-accesskeysecret: 
  oss-bucketname:

