server:
  port: 8084
spring:
  application:
    name: 
  datasource:
    driver-class-name:
    username: root
    password: 1234
    url: 
    type: 

  data:
    redis:
      host: 
      port: 
      password: 

  mvc:
    hiddenmethod:
      filter:
        enabled: 
    format:
      date:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
