server:
  port:
spring:
  application:
    name: 
  data:
    redis:
      host: 
      port:
      password: 

  cloud:
    gateway:
      routes:
        - id: 
          uri: 
          predicates:
            
          filters:
            - name:  #gateway提供限流内部工具类名称
              args:
                key-resolver: 
                redis-rate-limiter.replenishRate: 10  #每秒填充令牌数量
                redis-rate-limiter.burstCapacity: 1000  #令牌桶的最大容量

        - id:
          uri: 
          predicates:
            

        - id: 
          uri: 
          predicates:
          

        - id: 
          uri: 
          predicates:
           

eureka:
  client:
    service-url:
      defaultZone:
