server:
  port: 8083
spring:
  application:
    name: 
  datasource:
    driver-class-name: 
    username: 
    password:
    url: 
    type: 

  data:
    redis:
      host: 
      port: 
      password: 

  mvc:
    hiddenmethod:
      filter:
        enabled: 
    format:
      date:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: 
    log-impl: 

eureka:
  client:
    service-url:
      defaultZone:

alinfo:
  oss-endpoint:
  oss-accesskeyid:
  oss-accesskeysecret:
  oss-bucketname:
